### ISSUE TITLE
Java "package" should be translated into <meta/>

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#216] opened 2023-10-31 09:01 UTC
This is my Java:

```java
package foo;
class Foo {
}
```

I get this XMIR:

```xml
<program name="foo/Foo">
   <metas/>
   <objects>
      <o abstract="" name="foo/Foo">
        [...]
      </o>
   </objects>
</program>
```

I should be getting this instead:

```xml
<program name="Foo">
   <metas>
     <meta>
       <head>package</head>
       <tail>foo</tail>
     </meta>
   </metas>
   <objects>
      <o abstract="" name="Foo">
        [...]
      </o>
   </objects>
</program>
```

**Comment by volodya-lombrozo** [comment] 2023-10-31 09:29
@yegor256 Thank you. Let's do it. By the way, does it required for some optimizations? Or it's just for compliance with eo?

**Comment by yegor256** [comment] 2023-10-31 09:30
@volodya-lombrozo just for compliance between Java and EO -- they both have packages, would be great to match

**Comment by volodya-lombrozo** [comment] 2023-11-24 14:01
Duplicate of #271

**Closed by volodya-lombrozo** 2023-11-24 14:01 UTC
Labels: bug, duplicate
