### ISSUE TITLE
the `@line` attribute is optional, skip it

### ISSUE THREAD

**Issue by yegor256** [objectionary/jeo-maven-plugin#916] opened 2024-11-29 05:11 UTC
In the latest version of XMIR XSD, the `@line` attribute is optional. JEO may simply skip it.

**Comment by volodya-lombrozo** [comment] 2024-11-29 06:04
@yegor256 It are awesome news! Duplicate of https://github.com/objectionary/jeo-maven-plugin/issues/635

**Closed by volodya-lombrozo** 2024-11-29 06:04 UTC
